ManagerReceiver: ManagerReceiver.c DieWithError.c
	gcc ManagerReceiver.c DieWithError.c -o ManagerReceiver
ManagerSender: ManagerSender.c DieWithError.c
	gcc ManagerSender.c DieWithError.c -o ManagerSender
Decryptor: Decryptor.c DieWithError.c
	gcc Decryptor.c DieWithError.c HandleTCPClient.c -o Decryptor
